# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Plugins
gems:
    - jekyll-paginate

# Site settings
title:          Capsicum
tagline:        If pain must come, may it come quickly.
baseurl:        "/"
url:            http://rebeccabilbro.github.io
description: >
    <a href="https://twitter.com/rebeccabilbro">@rebeccabilbro's</a> development journal
author:
    name:       'Rebecca Bilbro'
    url:        https://github.com/rebeccabilbro
    github:     rebeccabilbro
    twitter:    rebeccabilbro

# Build settings
markdown:       kramdown
highlighter:    rouge
kramdown:
    input: GFM

# Custom Variables
paginate:       10
version:        1.0

github:
    repo:       https://github.com/rebeccabilbro/rebeccabilbro.github.io

theme: jekyll-theme-minimal